apiVersion: v1
kind: Pod
metadata:
  name: nginx-persist
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /data/nginx
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: nginx-pvc  