apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: result
  namespace: vote
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: result.example.com
      http:
        paths:
          - backend:
              serviceName: result
              servicePort: result-service
