apiVersion: v1
kind: Pod

metadata:
  name: alpine-all-vars
spec:
  containers:
    - name: alpine-test
      image: alpine
      command: ["/bin/sh", "-c", "env"]
      envFrom:
        - configMapRef:
            name: person-config
  restartPolicy: Never
